VERSION := $(shell git describe --tags --always --dirty)

all: build

version:
	@echo $(VERSION)

vet:
	go vet ./...
	cd grpc && go vet ./...
	cd vrpc && go vet ./...

test: vet
	go test -cover -race ./...
	cd grpc && go test -cover -race ./...
	cd vrpc && go test -cover -race ./...

build: test
	go build -v
	cd grpc && go build -v ./...
	cd vrpc && go build -v ./...

update:
	go get -u ./...

list:
	go list -m -json all | jq -r 'select(.GoVersion != null) | "\(.GoVersion) \(.Path)"' | sort -V
